# Generated by Django 5.1.7 on 2025-04-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('stationery', 'Stationery'), ('equipment', 'Equipment'), ('furniture', 'Furniture'), ('other', 'Other')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('threshold', models.PositiveIntegerField()),
                ('department', models.CharField(max_length=100)),
                ('last_restocked', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
